from typing import List
from pydantic import BaseModel, Field
from langchain_core.prompts import ChatPromptTemplate
from backend.agents.triage import InvestigationRequest
from backend.llm import build_llm, traced_config
from backend.observability.context import correlation_scope

class Hypothesis(BaseModel):
    """
    A single brainstormed theory about what might be causing the bug.
    """
    title: str = Field(description="Short title, e.g., 'Pydantic v2 Incompatibility'")
    description: str = Field(description="Detailed explanation of what might be failing")
    reason: str = Field(description="Why this hypothesis makes sense based on the bug report")
    expected_evidence: List[str] = Field(description="What clues we should look for in the code to prove this")
    investigation_plan: List[str] = Field(description="Step-by-step plan to investigate this hypothesis (e.g. 'Search for Pydantic imports', 'Check dependency graph')")

class HypothesisList(BaseModel):
    """
    A collection of hypotheses generated by the Hypothesis Agent.
    """
    hypotheses: List[Hypothesis]

class HypothesisAgent:
    """
    Takes an InvestigationRequest and uses divergent thinking to brainstorm multiple
    plausible root causes (hypotheses) before any code is actually searched.
    """
    def __init__(self, model_name: str = "meta-llama/llama-3.1-8b-instruct"):
        self.llm = build_llm(
            model_name=model_name,
            temperature=0.7,  # Higher temperature encourages more creative divergent thinking
        )
        
        self.structured_llm = self.llm.with_structured_output(HypothesisList)
        
        self.prompt = ChatPromptTemplate.from_messages([
            ("system", """You are a Senior Staff Software Engineer debugging a complex system.
You have been handed a triaged Investigation Request. 
Your job is to practice 'Divergent Thinking'. Do NOT immediately jump to a single conclusion.
Brainstorm a list of highly plausible hypotheses for what might be causing the issue.
For each hypothesis, detail the exact evidence you would need to find in the codebase to prove it is true, and write a short investigation plan.

Generate as many distinct hypotheses as you think are necessary to thoroughly cover the possibilities (usually 2-4).

Bug Type: {bug_type}
Affected Endpoint/Area: {affected_endpoint}
Suspected Component: {suspected_area}
Observed Behavior: {observed_behavior}
Expected Behavior: {expected_behavior}
Constraints: {constraints}
"""),
        ])
        
    def generate_hypotheses(self, request: InvestigationRequest) -> HypothesisList:
        """
        Generates hypotheses based on the provided InvestigationRequest.
        """
        chain = self.prompt | self.structured_llm
        
        with correlation_scope(node="hypothesis"):
            result = chain.invoke({
                "bug_type": request.bug_type,
                "affected_endpoint": request.affected_endpoint or "Unknown",
                "suspected_area": request.suspected_area,
                "observed_behavior": request.observed_behavior,
                "expected_behavior": request.expected_behavior,
                "constraints": ", ".join(request.constraints) if request.constraints else "None"
            }, config=traced_config())
        
        return result
